### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by spookylukey** [jneen/parsy#6]
Hello!

This looks like a really useful project for my needs, but the lack of a release for changes makes me think this is abandoned. Is it worth me submitting PRs? Do you want help maintaining it? I'd also like to overhaul the documentation, possibly using something like https://readthedocs.org/ - would that be accepted?

Thanks!

**Comment by jneen** [comment]
Hi @spookylukey, I don't maintain this anymore. If you'd like to take it over, feel free to fork. I don't remember if I ever pushed it to pypy but I'm happy to transfer that ownership as well.

**Comment by spookylukey** [comment]
Yes, version on PyPI is 0.0.4. My username on PyPI is spookylukey if you want to transfer ownership. Thanks!

**Comment by spookylukey** [comment]
Hi @jneen 

I've created a new organisation to host the project (to allow other people to join and take over the project in future more easily), and created a new repo at https://github.com/python-parsy/parsy

I've also done a lot of work on documentation - http://parsy.readthedocs.io/en/latest/ - and added TravisCI integration.

If you could give me permissions on PyPI, that would be great, I'd be all set to do new releases. Thanks!

**Comment by jneen** [comment]
Wonderful! I can't seem to figure out how to transfer control, if you could help me figure that out I'm happy to do the thing.

**Comment by bugaevc** [comment]
Hi, I'd like to join the new organization, if possible. I have contributed to parsy in the past and have a few ideas about what to do next (starting with my two year old pull request that's still hanging there unmerged).

**Comment by jneen** [comment]
I believe I've added you as an Owner, and I leave it to you from here. One thing I recommend doing is the same improvement we made in Parsimmon, which is to aggregate all error messages that occur at the same index, instead of only choosing one of them (i.e. make `expected` a list, and special case in `Result.aggregate` for when `self.index == other.index`)

**Comment by jneen** [comment]
Also if you can think of a better name for `generate`, I was kinda grasping at straws for that one.

**Comment by jneen** [comment]
(also, someone mentioned to me that this would also be possible in python 2.x, but i'm not sure how much i believe them...)

**Comment by spookylukey** [comment]
@jneen thanks so much, I can see I'm added as Owner on PyPI, that should be all I need. Thanks you for being a responsive past maintainer who was willing to hand over control :-)

@bugaevc it would be great if you could contribute. I'll add you to the org. It would be good if we could bounce our PRs off each other for review. I'm going to leave some comments on your existing one.

**Comment by bugaevc** [comment]
@spookylukey sounds great!

**Comment by bugaevc** [comment]
* @spookylukey your membership in the organization is _private_, meaning other people can't see you're a member, is that intended?
* Shouldn't @jneen be a member as well?

**Comment by spookylukey** [comment]
@bugaevc thanks for letting me know, still getting used to GitHub's roles. I've invited @jneen (I won't be offended if you turn it down, that's fine!), and I've made you an "Owner". I'm envisaging that I will take responsibility for the project for the time being, but having someone else as an Owner reduces the bus factor. Is that OK? If not, I'll drop you back to "Member".

**Comment by bugaevc** [comment]
Sure it is! Thanks.
